image: Visual Studio 2017
platform: x86
configuration: Debug

shallow_clone: true
clone_depth: 1

matrix:
  fast_finish: false # set this flag to immediately finish build once one of the jobs fails.

init:
  - ps: 'Write-Host "Configuring VS2017 x86 Native environment:" -ForegroundColor Magenta'
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvars32.bat"

build: off

build_script:
  - ps: 'Write-Host "Building $env:APPVEYOR_PROJECT_NAME:" -ForegroundColor Magenta'
  - cmd: namke /f Makefile.nmake
