image: Visual Studio 2017
platform: x86
configuration: Debug

shallow_clone: true
clone_depth: 1

matrix:
  fast_finish: false # set this flag to immediately finish build once one of the jobs fails.

init:
  - ps: 'Write-Host "Configuring VS2017 x86 Native environment:" -ForegroundColor Magenta'
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"

install:
  - ps: |
      Write-Host "Installing Dr. Memory 1.11.0:" -ForegroundColor Magenta
      $msiPath = "$($env:USERPROFILE)\DrMemory-Windows-1.11.0-2.msi"
      (New-Object Net.WebClient).DownloadFile('https://github.com/DynamoRIO/drmemory/releases/download/release_1.11.0/DrMemory-Windows-1.11.0-2.msi', $msiPath)
      cmd /c start /wait msiexec /i $msiPath /q
  - cmd: set PATH=%PATH%;"C:\Program Files (x86)\Dr. Memory\bin"
  - cmd: drmemory.exe -version 

build: off

before_build:
  - ps: |
      Write-Host "Build worker environment variables:" -ForegroundColor Magenta
      Get-ChildItem Env: | %{"{0}={1}" -f $_.Name,$_.Value}
  - cmd: mkdir .\logs

build_script:
  - ps: 'Write-Host "Building fuzz_me.exe:" -ForegroundColor Magenta'
  - cmd: nmake /f Makefile.nmake

test_script:
  - ps: 'Write-Host "Running fuzz_me.exe:" -ForegroundColor Magenta'
  - cmd: .\fuzz_me.exe
  - ps: 'Write-Host "Running symquery.exe searching for DrMemoryFuzzerTest:" -ForegroundColor Magenta'
  - cmd: symquery.exe -e fuzz_me.exe -v --searchall -s DrMemoryFuzzerTest
  - ps: 'Write-Host "Running drmemory.exe:" -ForegroundColor Magenta'
  - cmd: drmemory.exe -quiet -batch -verbose 3 -logdir .\logs -fuzz -fuzz_function DrMemoryFuzzerTest -- fuzz_me.exe 

after_test:
  - ps: 'Write-Host "Dumping Dr. Memory logs:" -ForegroundColor Magenta'
  - ps: |
      Get-ChildItem -Recurse -Path .\logs\DrMemory-fuzz* | % { 
        Write-Host "####### $_ ######" -ForegroundColor Magenta
        Get-Content $_
      }
