image: Visual Studio 2017
platform: x86
configuration: Debug

shallow_clone: true
clone_depth: 1

matrix:
  fast_finish: false # set this flag to immediately finish build once one of the jobs fails.

init:
  - ps: 'Write-Host "Configuring VS2017 x86 Native environment:" -ForegroundColor Magenta'
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"

install:
- ps: |
    Write-Host "Installing Dr. Memory 1.11.0:" -ForegroundColor Magenta
    $drmemoryMsi = "$($env:TEMP)\DrMemory-Windows-1.11.0-2.msi"
    (New-Object Net.WebClient).DownloadFile('https://github.com/DynamoRIO/drmemory/releases/download/release_1.11.0/DrMemory-Windows-1.11.0-2.msi', $drmemoryMsi)
    msiexec /i $drmemoryMsi /quiet /qn /norestart
    $env:Path += "C:\Program Files (x86)\Dr. Memory\bin"
    drmemory.exe -version

build: off

before_build:
  - ps: |
      Write-Host "Build worker environment variables:" -ForegroundColor Magenta
      Get-ChildItem Env: | %{"{0}={1}" -f $_.Name,$_.Value}

build_script:
  - ps: 'Write-Host Building $env:APPVEYOR_PROJECT_NAME: -ForegroundColor Magenta'
  - cmd: nmake /f Makefile.nmake

test_script:
  - cmd: .\fuzz_me.exe
